name: Deploy to EC2
on:
  push:
    branches:
      - master #branch on which your code is pushed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            # Commands to deploy the React app
            cd /Downloads/test1
            npm install
            npm run build
            npm i serve
            serve -p 3000 build/


