
name: Build on Package Version Change

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Check for Package Version Change
        id: check_version
        run: |
          PACKAGE_VERSION=$(node -p "require('./node_modules/my-utils/package.json').version")
          
          echo "::set-output name=package_version::$PACKAGE_VERSION"

      - name: Trigger Build on Package Version Change
        if: steps.check_version.outputs.package_version != ${{ github.event.before }}
        run: echo "Version changed. Triggering build..."